spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
  datasource:
    data: classpath:data-mysql.sql # 시작할때 실행시킬 script
    url: jdbc:mysql://localhost:3306/posts?serverTimezone=UTC&characterEncoding=UTF-8
    username: springboot
    password: spring
    initialization-mode: always # 이걸 써줘야 H2같은 내장 말고 외장 DB가 초기화 됨.
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      #ddl-auto: create-drop # 이 설정이 있으면 table 이 drop -> create됨.