GET http://localhost:8080/posts/1
Content-Type: application/json

###

GET http://localhost:8080/posts
Content-Type: application/json

###

GET http://localhost:8080/students/2
Content-Type: application/json

###