PUT http://localhost:8080/posts/3
Content-Type: application/json

{
  "title": "updatetest",
  "content": "test content",
  "author": "teste23232r"
}

###

PUT http://localhost:8080/students/2
Content-Type: application/json

{
  "password": "update password",
  "birthDay": "update birthDay",
  "phone": "update phone",
  "email": "update emailemail"
}

###